name: Multi-shell Hello world

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print via bash
        run: echo "Hello World from bash"
        shell: bash

      - name: Print via PowerShell
        run: echo "Hello World from PowerShell"
        shell: pwsh

      - name: Print via Python
        run: python -c 'print("Hello World from Python")'
        shell: python 
