name : Pull request with path filtering
on:
    pull_request:
        branches:
            - main
        paths:
            - "src/**"
jobs:
    one-job:
        runs-on: ubuntu-latest
        steps:
            - name : pull request
              run: echo "Pull Request"            
            